name: food_order_app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  d_info: ^0.2.2
  flutter:
    sdk: flutter
  gap: ^3.0.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/download.jpg
  - assets/anime.jpg
  - assets/anime2.png
  - assets/bro.jpg
  - assets/spageti.jpg
